services:
  prosody:
    image: prosody/prosody:latest
    container_name: prosody
    ports:
      - "5222:5222"
      - "5269:5269"
    volumes:
      - ./prosody.cfg.lua:/etc/prosody/prosody.cfg.lua:ro
      - ./certs:/etc/prosody/certs:ro
    networks:
      xmpp_network:
        ipv4_address: 172.20.0.2

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./certs:/app/certs:ro # Mount certificates in the app container
    environment:
      - XMPP_JID=client@prosody
      - XMPP_PASSWORD=password
      - ROBOT_RECIPIENT=alpha-pi-zero-agent@prosody
      - ROBOT_INSTRUCTIONS=forward,backward,left,right,stop
    extra_hosts:
      - "prosody:172.20.0.2"
    depends_on:
      - prosody
    networks:
      - xmpp_network

networks:
  xmpp_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
