services:
  prosody:
    image: prosody/prosody:latest
    container_name: prosody
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
      - "5281:5281"
    volumes:
      - ./prosody.cfg.lua:/etc/prosody/prosody.cfg.lua:ro
      - ./certs:/etc/prosody/certs:ro
      - ./modules:/usr/lib/prosody/modules-extra:ro
    networks:
      xmpp_network:
        ipv4_address: 172.20.0.3

  api:
    image: oven/bun:latest
    container_name: xmpp_api
    depends_on:
      - prosody
    working_dir: /app
    volumes:
      - ./api:/app
    command: /bin/sh -c "bun install && bun run start"
    ports:
      - "3000:3000"
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    networks:
      xmpp_network:
        ipv4_address: 172.20.0.4
    extra_hosts:
      - "prosody:172.20.0.3"
      - "internal-api:172.20.0.6"

  dashboard:
    image: dij0s/expose:latest
    container_name: xmpp_dashboard
    depends_on:
      - api
    ports:
      - "8888:8888"
    networks:
      xmpp_network:
        ipv4_address: 172.20.0.5

networks:
  xmpp_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
